export const
    GAME_TIME = 5 * 60,
    GAME_SCORE_TO_WIN = 5,

    BOARD_WIDTH = 640,
    BOARD_HEIGHT = 480,
    BOARD_GOAL_SIZE = 200,

    BALL_SIZE = 32,
    BALL_SPEED = 512,

    PADDLE_WIDTH = 16,
    PADDLE_HEIGHT = 100,
    PADDLE_GOAL_OFFSET = 32,
    PADDLE_SPEED = 384;

